package com.bankingSystem.customer_ms.model;

import jakarta.persistence.*;
import lombok.*;

import javax.validation.constraints.NotNull;

/**
 * Entity class representing a customer in the banking system.
 * <p>
 * This class is annotated with JPA annotations to define it as a persistent entity
 * to be mapped to the "customer" table in the database. It includes fields for
 * customer details such as name, DNI (unique identification), and email.
 * </p>
 */
@Data
@Entity
@Table(name = "customer")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Customer {

    /**
     * The unique identifier for the customer.
     * <p>
     * This field is marked with {@link Id} and {@link GeneratedValue} annotations
     * to indicate that it is the primary key and its value will be automatically
     * generated by the database.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer customerId;

    /**
     * The first name of the customer.
     * <p>
     * This field is annotated with {@link NotNull} to indicate that it must not be null
     * when persisted in the database.
     * </p>
     */
    @NotNull
    @Column(name = "first_name")
    private String firstName;

    /**
     * The last name of the customer.
     * <p>
     * This field is annotated with {@link NotNull} to indicate that it must not be null
     * when persisted in the database.
     * </p>
     */
    @NotNull
    @Column(name = "last_name")
    private String lastName;

    /**
     * The DNI (identification number) of the customer.
     * <p>
     * This field is unique and marked with {@link NotNull} to ensure that every customer
     * has a unique identification number.
     * </p>
     */
    @NotNull
    @Column(unique = true, name="dni")
    private String dni;

    /**
     * The email address of the customer.
     * <p>
     * This field is annotated with {@link NotNull} to indicate that it must not be null
     * when persisted in the database.
     * </p>
     */
    @NotNull
    @Column(name = "email")
    private String email;
}
